apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spre-oppgaver
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: /isalive
    initialDelay: 20
  readiness:
    path: /isready
    initialDelay: 20
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspreoppgaver
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_RESET_POLICY
      value: none
    - name: KAFKA_RAPID_TOPIC
      value: helse-rapid-v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: spre-oppgaver-v1
    - name: DATABASE_HOST
      value: a01dbvl011.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: spre-oppgaver
    - name: VAULT_MOUNTPATH
      value: postgresql/prod-fss/
